apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uat

resources:
- ../../base

commonLabels:
  environment: uat

replicas:
- name: backend
  count: 2
- name: frontend
  count: 2

images:
- name: microservice-app-backend
  newTag: uat-latest
- name: microservice-app-frontend
  newTag: uat-latest

patchesStrategicMerge:
- resources.yaml
